from deep_translator import GoogleTranslator
from functools import lru_cache

class PromptService:
    """
    Servicio para generar y traducir dinámicamente los prompts según el idioma
    del chat, evitando así el sesgo de idioma del LLM.
    """

    # Mapeo básico de nombres de idioma a códigos para el traductor
    LANG_MAP = {
        "english": "en",
        "spanish": "es",
        "french": "fr",
        "german": "de",
        "italian": "it",
        "portuguese": "pt",
        "dutch": "nl",
        "russian": "ru",
        "japanese": "ja",
        "korean": "ko",
        "chinese": "zh-CN"
    }

    @staticmethod
    def _get_lang_code(language_str: str) -> str:
        clean_lang = language_str.lower().strip()
        return PromptService.LANG_MAP.get(clean_lang, "en")  # Default to en

    @staticmethod
    @lru_cache(maxsize=128)
    def _translate_cached(text: str, target_lang_code: str) -> str:
        if target_lang_code == "en":
            return text
        try:
            translator = GoogleTranslator(source='auto', target=target_lang_code)
            return translator.translate(text)
        except Exception as e:
            print(f"Translation error in PromptService: {e}")
            return text  # Fallback a inglés si falla

    @classmethod
    def get_generate_node_system_context(cls, language: str, name: str, description: str, role: str, review_feedback: str, room_summary: str = None) -> str:
        lang_code = cls._get_lang_code(language)
        
        base_text = f"You are {name}. Your personality: {description}. Your role: {role}."
        if room_summary:
            base_text += f"\nConversation Summary so far: {room_summary}"
            
        translated_base = cls._translate_cached(base_text, lang_code)
        
        feedback_text = ""
        if review_feedback and review_feedback != 'None':
            fb_base = f"Review feedback from previous attempt: {review_feedback}"
            feedback_text = "\n" + cls._translate_cached(fb_base, lang_code)
            
        return f"{translated_base}{feedback_text}"

    @classmethod
    def get_chat_response_rules(cls, language: str, context_words: list[str]) -> str:
        lang_code = cls._get_lang_code(language)
        
        vocab_text = ""
        if context_words:
            v_base = f"YOUR MAIN MISSION: You MUST naturally use at least one or two of the following words in your response: {', '.join(context_words)}."
            vocab_text = cls._translate_cached(v_base, lang_code)
            
        rules_base = "Keep the conversation flowing, ask open-ended questions, and respond with interest according to your role."
        translated_rules = cls._translate_cached(rules_base, lang_code)
        
        json_rule_base = "CRITICAL: ALWAYS return a valid JSON object with the following format. Do not add markdown or extra text:"
        translated_json_rule = cls._translate_cached(json_rule_base, lang_code)
        
        return f"""
        {translated_rules}
        {vocab_text}
        
        {translated_json_rule}
        {{
            "response": "Your generated response here"
        }}
        """

    @classmethod
    def get_review_node_prompt(cls, language: str, role: str, message: str) -> str:
        lang_code = cls._get_lang_code(language)
        
        base_prompt = f"""
        Evaluate the following message generated by an AI playing a role.
        If the AI does not follow the rules set for this exercise, mark it as invalid.
        Role: {role if role else 'None'}
        Language required: {language}
        Message: "{message}"
        
        Respond ONLY with a JSON object:
        {{
            "is_valid": true/false,
            "failed_criteria": ["rol", "idioma", "contexto", "coherencia"] (empty if valid),
            "correction_instructions": "What needs to change" (empty if valid)
        }}
        """
        # Para el revisor (que requiere formato JSON estricto), a veces es mejor mantener
        # las instrucciones del JSON en inglés, pero traducimos el contexto.
        # Aquí dejaremos el prompt del revisor mayormente en inglés ya que es un proceso
        # interno del sistema y el inglés es más robusto para outputs JSON tipados.
        return base_prompt
