"""Refactor chat architecture

Revision ID: 46f1f1ccf3c3
Revises: b8c9d0e1f2g3
Create Date: 2026-05-14 18:39:36.581928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f1f1ccf3c3'
down_revision: Union[str, Sequence[str], None] = 'b8c9d0e1f2g3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=True),
    sa.Column('ai_name', sa.String(), nullable=True),
    sa.Column('ai_gender', sa.String(), nullable=True),
    sa.Column('ai_personality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_participants_id'), 'chat_participants', ['id'], unique=False)
    op.add_column('chat_messages', sa.Column('participant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chat_messages_sender_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'sender_id')
    op.add_column('chat_rooms', sa.Column('name', sa.String(), nullable=False))
    op.add_column('chat_rooms', sa.Column('description', sa.String(), nullable=True))
    op.add_column('chat_rooms', sa.Column('context', sa.String(), nullable=True))
    op.add_column('chat_rooms', sa.Column('language', sa.String(), nullable=False))
    op.add_column('chat_rooms', sa.Column('created_by', sa.String(), nullable=False))
    op.drop_constraint(op.f('chat_rooms_human_user_id_fkey'), 'chat_rooms', type_='foreignkey')
    op.drop_constraint(op.f('chat_rooms_user1_id_fkey'), 'chat_rooms', type_='foreignkey')
    op.drop_constraint(op.f('chat_rooms_user2_id_fkey'), 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'chat_rooms', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_rooms', 'human_user_id')
    op.drop_column('chat_rooms', 'user1_id')
    op.drop_column('chat_rooms', 'user2_id')
    op.drop_column('chat_rooms', 'is_ai_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('is_ai_chat', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('chat_rooms', sa.Column('user2_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chat_rooms', sa.Column('user1_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chat_rooms', sa.Column('human_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(op.f('chat_rooms_user2_id_fkey'), 'chat_rooms', 'users', ['user2_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_rooms_user1_id_fkey'), 'chat_rooms', 'users', ['user1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_rooms_human_user_id_fkey'), 'chat_rooms', 'users', ['human_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_rooms', 'created_by')
    op.drop_column('chat_rooms', 'language')
    op.drop_column('chat_rooms', 'context')
    op.drop_column('chat_rooms', 'description')
    op.drop_column('chat_rooms', 'name')
    op.add_column('chat_messages', sa.Column('sender_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_sender_id_fkey'), 'chat_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'participant_id')
    op.drop_index(op.f('ix_chat_participants_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    # ### end Alembic commands ###
