"""Add CachedDictionaryWord table

Revision ID: 48f4529e7a5f
Revises: f4d4be4eff52
Create Date: 2026-06-12 15:14:37.761529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f4529e7a5f'
down_revision: Union[str, Sequence[str], None] = 'f4d4be4eff52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_dictionary_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'language', 'target_language', name='uq_cached_word')
    )
    op.create_index(op.f('ix_cached_dictionary_words_id'), 'cached_dictionary_words', ['id'], unique=False)
    op.create_index(op.f('ix_cached_dictionary_words_word'), 'cached_dictionary_words', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cached_dictionary_words_word'), table_name='cached_dictionary_words')
    op.drop_index(op.f('ix_cached_dictionary_words_id'), table_name='cached_dictionary_words')
    op.drop_table('cached_dictionary_words')
    # ### end Alembic commands ###
