"""add vocabulary and words table

Revision ID: 8ad53c573b5e
Revises: 06c60814250e
Create Date: 2026-05-02 09:26:54.457161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ad53c573b5e'
down_revision: Union[str, Sequence[str], None] = '06c60814250e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_lists_id'), 'vocabulary_lists', ['id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('past', sa.String(), nullable=True),
    sa.Column('gerund', sa.String(), nullable=True),
    sa.Column('participle', sa.String(), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('word_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('examples', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('synonyms', sa.String(), nullable=True),
    sa.Column('antonyms', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_name'), 'words', ['name'], unique=False)
    op.create_table('list_word_association',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['vocabulary_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_word_association')
    op.drop_index(op.f('ix_words_name'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_vocabulary_lists_id'), table_name='vocabulary_lists')
    op.drop_table('vocabulary_lists')
    # ### end Alembic commands ###
