"""add streak fields to profile

Revision ID: c3521d1ce3a4
Revises: de934c51b3fa
Create Date: 2026-05-16 17:02:47.819353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3521d1ce3a4'
down_revision: Union[str, Sequence[str], None] = 'de934c51b3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_activity_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'last_activity_date')
    op.drop_column('user_profiles', 'longest_streak')
    op.drop_column('user_profiles', 'current_streak')
    # ### end Alembic commands ###
