"""Add Hybrid Memory summary to ChatRoom

Revision ID: de934c51b3fa
Revises: 0b96be2bfecb
Create Date: 2026-05-16 11:39:24.689883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de934c51b3fa'
down_revision: Union[str, Sequence[str], None] = '0b96be2bfecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('chat_rooms', sa.Column('last_summarized_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'last_summarized_message_id')
    op.drop_column('chat_rooms', 'summary')
    # ### end Alembic commands ###
